"""initial schema

Revision ID: 527e7e5db2c4
Revises: 
Create Date: 2026-09-07 17:26:50.287137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '527e7e5db2c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('licence_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('licence_class', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='licenceclass'), nullable=False),
    sa.Column('licence_issue_date', sa.DateTime(), nullable=False),
    sa.Column('licence_expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISQUALIFIED', 'EXPIRED', name='driverstatus'), nullable=False),
    sa.Column('restrictions', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id_number'), 'drivers', ['id_number'], unique=False)
    op.create_index(op.f('ix_drivers_licence_number'), 'drivers', ['licence_number'], unique=True)
    op.create_table('notification_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('channels', sa.String(length=200), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_event')
    )
    op.create_table('psv_operators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('licence_number', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='psvoperatorstatus'), nullable=False),
    sa.Column('registered_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licence_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'OFFICER', 'TOLL_OPERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_id_number', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('engine_number', sa.String(length=100), nullable=True),
    sa.Column('chassis_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEREGISTERED', 'STOLEN', name='vehiclestatus'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_owner_id_number'), 'vehicles', ['owner_id_number'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.create_table('accidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'SERIOUS', 'FATAL', name='accidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'UNDER_INVESTIGATION', 'INVESTIGATED', 'CLOSED', name='accidentstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anpr_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anpr_events_plate_number'), 'anpr_events', ['plate_number'], unique=False)
    op.create_index(op.f('ix_anpr_events_vehicle_id'), 'anpr_events', ['vehicle_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_centre', sa.String(length=200), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('result', sa.Enum('PASSED', 'FAILED', 'PENDING', name='inspectionresult'), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('inspected_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_vehicle_id'), 'inspections', ['vehicle_id'], unique=False)
    op.create_table('insurance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policy_number'), 'insurance', ['policy_number'], unique=True)
    op.create_index(op.f('ix_insurance_vehicle_id'), 'insurance', ['vehicle_id'], unique=False)
    op.create_table('licence_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('requested_class', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='licenceclass'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'THEORY_TEST_SCHEDULED', 'THEORY_TEST_PASSED', 'THEORY_TEST_FAILED', 'PRACTICAL_TEST_SCHEDULED', 'PRACTICAL_TEST_PASSED', 'PRACTICAL_TEST_FAILED', 'ISSUED', 'REJECTED', name='licenceapplicationstatus'), nullable=False),
    sa.Column('theory_score', sa.Integer(), nullable=True),
    sa.Column('practical_score', sa.Integer(), nullable=True),
    sa.Column('issued_licence_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licence_applications_applicant_id'), 'licence_applications', ['applicant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.Enum('FINE', 'FEE', 'PERMIT', 'TOLL', name='paymenttype'), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('paid_by', sa.Uuid(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_related_entity_id'), 'payments', ['related_entity_id'], unique=False)
    op.create_table('psv_permits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('permit_number', sa.String(length=50), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'SUSPENDED', name='psvpermitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['psv_operators.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_number')
    )
    op.create_index(op.f('ix_psv_permits_operator_id'), 'psv_permits', ['operator_id'], unique=False)
    op.create_index(op.f('ix_psv_permits_vehicle_id'), 'psv_permits', ['vehicle_id'], unique=False)
    op.create_table('toll_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('gate_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('compliance_result', sa.Enum('COMPLIANT', 'FLAGGED', name='tollcomplianceresult'), nullable=False),
    sa.Column('flagged_issues', sa.Text(), nullable=True),
    sa.Column('toll_amount', sa.Integer(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toll_transactions_plate_number'), 'toll_transactions', ['plate_number'], unique=False)
    op.create_index(op.f('ix_toll_transactions_vehicle_id'), 'toll_transactions', ['vehicle_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('violation_type', sa.Enum('SPEEDING', 'RUNNING_RED_LIGHT', 'NO_INSURANCE', 'EXPIRED_FITNESS', 'NO_PSV_PERMIT', 'DRIVING_WITHOUT_LICENCE', 'ILLEGAL_PARKING', 'OVERLOADING', 'REAR_SEAT_BELT', 'USING_PHONE', 'BLACKLISTED_VEHICLE', 'OTHER', name='violationtype'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_vehicle_id'), 'violations', ['vehicle_id'], unique=False)
    op.create_table('accident_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accident_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accident_id'], ['accidents.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_vehicles_accident_id'), 'accident_vehicles', ['accident_id'], unique=False)
    op.create_table('challans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('penalty_amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'OVERDUE', 'DISPUTED', name='challanstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challans_reference'), 'challans', ['reference'], unique=True)
    op.create_index(op.f('ix_challans_vehicle_id'), 'challans', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_challans_violation_id'), 'challans', ['violation_id'], unique=False)
    op.create_table('fitness_certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_index(op.f('ix_fitness_certificates_inspection_id'), 'fitness_certificates', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_fitness_certificates_vehicle_id'), 'fitness_certificates', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fitness_certificates_vehicle_id'), table_name='fitness_certificates')
    op.drop_index(op.f('ix_fitness_certificates_inspection_id'), table_name='fitness_certificates')
    op.drop_table('fitness_certificates')
    op.drop_index(op.f('ix_challans_violation_id'), table_name='challans')
    op.drop_index(op.f('ix_challans_vehicle_id'), table_name='challans')
    op.drop_index(op.f('ix_challans_reference'), table_name='challans')
    op.drop_table('challans')
    op.drop_index(op.f('ix_accident_vehicles_accident_id'), table_name='accident_vehicles')
    op.drop_table('accident_vehicles')
    op.drop_index(op.f('ix_violations_vehicle_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_toll_transactions_vehicle_id'), table_name='toll_transactions')
    op.drop_index(op.f('ix_toll_transactions_plate_number'), table_name='toll_transactions')
    op.drop_table('toll_transactions')
    op.drop_index(op.f('ix_psv_permits_vehicle_id'), table_name='psv_permits')
    op.drop_index(op.f('ix_psv_permits_operator_id'), table_name='psv_permits')
    op.drop_table('psv_permits')
    op.drop_index(op.f('ix_payments_related_entity_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_licence_applications_applicant_id'), table_name='licence_applications')
    op.drop_table('licence_applications')
    op.drop_index(op.f('ix_insurance_vehicle_id'), table_name='insurance')
    op.drop_index(op.f('ix_insurance_policy_number'), table_name='insurance')
    op.drop_table('insurance')
    op.drop_index(op.f('ix_inspections_vehicle_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_anpr_events_vehicle_id'), table_name='anpr_events')
    op.drop_index(op.f('ix_anpr_events_plate_number'), table_name='anpr_events')
    op.drop_table('anpr_events')
    op.drop_table('accidents')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_owner_id_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('psv_operators')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_drivers_licence_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id_number'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
