"""road network and user links

Revision ID: f0a1f8296810
Revises: 527e7e5db2c4
Create Date: 2026-09-07 17:57:13.466565
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0a1f8296810'
down_revision: Union[str, None] = '527e7e5db2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intersections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('road_class', sa.Enum('HIGHWAY', 'MAIN_ROAD', 'SECONDARY', 'ACCESS', name='roadclass'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONGESTED', 'UNDER_MAINTENANCE', 'CLOSED', name='roadstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('road_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('road_id', sa.Uuid(), nullable=False),
    sa.Column('start_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('end_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('travel_minutes', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['end_intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['start_intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_segments_end_intersection_id'), 'road_segments', ['end_intersection_id'], unique=False)
    op.create_index(op.f('ix_road_segments_road_id'), 'road_segments', ['road_id'], unique=False)
    op.create_index(op.f('ix_road_segments_start_intersection_id'), 'road_segments', ['start_intersection_id'], unique=False)
    op.create_table('route_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('origin_intersection_id', sa.Uuid(), nullable=False),
    sa.Column('destination_intersection_id', sa.Uuid(), nullable=True),
    sa.Column('raw_route', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_intersection_id'], ['intersections.id'], ),
    sa.ForeignKeyConstraint(['origin_intersection_id'], ['intersections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_cache_destination_intersection_id'), 'route_cache', ['destination_intersection_id'], unique=False)
    op.create_index(op.f('ix_route_cache_origin_intersection_id'), 'route_cache', ['origin_intersection_id'], unique=False)
    op.create_table('road_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_type', sa.Enum('ACCIDENT', 'ROAD_CLOSED', 'MAINTENANCE', 'CONGESTION', 'ROADWORKS', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'SERIOUS', 'FATAL', name='incidentseverity'), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=True),
    sa.Column('road_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reported_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['road_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_incidents_incident_type'), 'road_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_road_incidents_is_active'), 'road_incidents', ['is_active'], unique=False)
    op.create_index(op.f('ix_road_incidents_road_id'), 'road_incidents', ['road_id'], unique=False)
    op.create_index(op.f('ix_road_incidents_segment_id'), 'road_incidents', ['segment_id'], unique=False)
    with op.batch_alter_table('drivers') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(op.f('ix_drivers_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_drivers_user_id', 'users', ['user_id'], ['id'])
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(op.f('ix_vehicles_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_vehicles_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.drop_constraint('fk_vehicles_user_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_vehicles_user_id'))
        batch_op.drop_column('user_id')
    with op.batch_alter_table('drivers') as batch_op:
        batch_op.drop_constraint('fk_drivers_user_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_drivers_user_id'))
        batch_op.drop_column('user_id')
    op.drop_index(op.f('ix_road_incidents_segment_id'), table_name='road_incidents')
    op.drop_index(op.f('ix_road_incidents_road_id'), table_name='road_incidents')
    op.drop_index(op.f('ix_road_incidents_is_active'), table_name='road_incidents')
    op.drop_index(op.f('ix_road_incidents_incident_type'), table_name='road_incidents')
    op.drop_table('road_incidents')
    op.drop_index(op.f('ix_route_cache_origin_intersection_id'), table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_destination_intersection_id'), table_name='route_cache')
    op.drop_table('route_cache')
    op.drop_index(op.f('ix_road_segments_start_intersection_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_road_id'), table_name='road_segments')
    op.drop_index(op.f('ix_road_segments_end_intersection_id'), table_name='road_segments')
    op.drop_table('road_segments')
    op.drop_table('roads')
    op.drop_table('intersections')
    # ### end Alembic commands ###
